### ISSUE TITLE
Features to add to the "Like" page.

### ISSUE THREAD

**Issue by vbinetruy** [MASASFM/masas#4]
On the "Like" page:

-Add search bar to search a song you have liked (search bar will be unique to this page);

-Add sorting option by hashtags: #EarlyMorning, #LateMorning, #EarlyAfternoon, #LateAfternoon, #Evening, #Night. (Each track on the system is assigned **one** of those "hashtags").

**Comment by tbinetruy** [comment]
I'll do that asap. I need micka to design it though.

**Comment by mickamasas** [comment]
That's a cool feature we will have to implement, but later. Users have to logged-in, have to discover new sounds, have to understand our fucking diamond to like a sound, get back to the like page, remember the name of the sound because they don't want to scroll because they have to much likes. This goes to 0,0001% of users for the next months to go, no?

**Comment by vbinetruy** [comment]
Micka, all of this has to be done now. We are perfecting what we have now (Profile, Discover, Popular, Upload, Likes Page, algorithms...) so that when we can start the Public Beta (and only work on new features once it has started)

The point being, we need all of this to be done as fast as possible because everyone uses the mobile website but right now, it is fucking unbearable! So users don't stay! (there are a thousand different online music businesses that try to make, a thousand choices for the customer...the modern consumer is very, very demanding, and little shits like that will make them leave)

This is just one of the many issues that have to be fixed, and it has to be fixed! Why wait when it is something that can be done relatively fast and easily?
