### ISSUE TITLE
Pop up log-in

### ISSUE THREAD

**Issue by mickamasas** [MASASFM/masas#79]
New pop-up log-in have a position trouble in bigger screen <13'. Flex-box alignement seems to have trouble - I've try to edit it manually with my notes but impossible to find the right combination..

**Comment by vbinetruy** [comment]
This was a try out for a log-in screen with 3 (or 4) different types of logins: Facebook, Twitter, Gmail, Email (but having just one is ugly! So we'll recenter it, for now).

Since we only have one for now (Facebook) and another one coming online this weekend (Google login) everything will be recentered.

Like that:

<img width="522" alt="screen shot 2017-01-20 at 11 28 46 am" src="https://cloud.githubusercontent.com/assets/19936607/22146058/b9810c16-df03-11e6-9afc-68568726d0e3.png">
<img width="316" alt="screen shot 2017-01-20 at 11 29 18 am" src="https://cloud.githubusercontent.com/assets/19936607/22146059/b981e32a-df03-11e6-87a0-749500f6ce9e.png">
