### ISSUE TITLE
[UI] Previous / Next track on mobile player

### ISSUE THREAD

**Issue by mickamasas** [MASASFM/masas#91]
Next track on mobile player is giant and need to be fixed. Previous track is invisible.

**Comment by tbinetruy** [comment]
Can you please provide screen shots ?
Can you please provide browser version ?
Can you please provide OS version ?
Can you please provide context of the bug ? (playing from wherever, from discover, from popular, from likes, from a profile's uploads.

I cannot do much without these answers as button geometry is fine on my devices and I haven't had any feedback from victor regarding this issue.

**Comment by tbinetruy** [comment]
Again. Previous track button is invisible for **which cases** ?

The button is not supposed to be visible:
-when playing from crowdradio 
-when it's the first song of discover / likes playlist / someone's profile.

similarly, the next button will be missing on the last song in your likes playlist and someone's profile.


Please carefully try to understand what you are doing when using the app. 


Please make a spec of when the next / previous player buttons are visible.


Keep in mind that the control button behaviors should be identical on mobile and desktop


Also, please let me know what should be done when the next / previous buttons are not available on the mobile player regarding up / down votes since, as you've observed, there is now a hole.
